/**
 * AUTO-GENERATED by type-bridge
 * Do not edit manually
 * Generated: 2025-11-01T16:20:06.274Z
 */

/** Auto-generated from prisma schema */
export interface User {
  id?: string | null;
  email: string;
  name: string;
  age?: number | null;
  rol: string;
  posts: Post[];
  profile?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

/** Auto-generated from prisma schema */
export interface Post {
  id?: string | null;
  title: string;
  content?: string | null;
  published: boolean;
  author: string;
  authorId: string;
  tags: string[];
  createdAt: Date;
}

/** Auto-generated from prisma schema */
export interface Profile {
  id?: string | null;
  bio: string;
  avatar?: string | null;
  user: string;
  userId: string;
}
